name: Ubuntu build (push)
on: [push]
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Cloned ${{ github.repository }}"

      - name: Install test dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y meson ninja-build
    
      - name: Checkout cache
        uses: actions/cache@v4
        with:
          path: |
            builddir
            subprojects
          key: ${{ github.workflow }}-builddir-${{ hashFiles('**/meson.build', '**/meson_options.txt', 'subprojects/*.wrap') }}

      - name: Setup meson build files
        run: |
          meson setup -Denable-tests=true builddir

      - name: Executing tests
        run: |
          cd builddir
          meson test -v

      - run: echo "Test status - ${{ job.status }}."
